### PR TITLE
Adding customisation for description prefix

### LINKED ISSUE #15: Allow customization of the description prefix
In https://github.com/taskcluster/tc-admin/blob/d35c775020e9a67086e58bd91203a7b611803187/tcadmin/resources/util.py#L16-L20 we add a prefix to every description that basically says "don't edit this".  We would like to allow users to customize this prefix in `tc-admin.py`, similar to how they can customize `check_path`: https://github.com/taskcluster/tc-admin/blob/d35c775020e9a67086e58bd91203a7b611803187/tcadmin/appconfig.py#L90

### PR DESCRIPTION
**Pull request by vishakhanihore**
Fixes #15

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@djmitche Please have a look

**Comment by vishakhanihore** [comment]
@djmitche I need help with `black and python tests`.
Also what sort of tests should I add?

**Comment by djmitche** [comment]
If you run `pip install black`, then you can run `black tcadmin` and it will do the reformatting for you.  Similarly, you can `pip install flake8` and then run `flake8 tcadmin` to see what it's complaining about -- but it won't fix those for you.  It looks like there's a syntax error, too, which will need to be fixed.

The option you've added is similar to check_path, and that's tested in `test/test_boot.py`, so you could probably just add to those tests.

**Comment by vishakhanihore** [comment]
```py
cls = <class 'tcadmin.appconfig.AppConfig'>
    @classmethod
    def current(cls):
        """Get the current AppConfig"""
>       assert getattr(cls, "_current", None), "no current AppConfig"
E       AssertionError: no current AppConfig
/repo/tcadmin/appconfig.py:113: AssertionError
```
@djmitche I dont think its related to my PR

**Comment by djmitche** [comment]
I think it is -- during the tests, the description_prefix function is being used in a context where there is no current AppConfig.

**Comment by vishakhanihore** [comment]
How do i create a instance for appconfig for this ?

**Comment by djmitche** [comment]
I think it would be best to create a [pytest fixture](https://docs.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code) that generates an appconfig and sets it as current for the duration of the test, using `appconfig._as_current`.  This could go into `tcadmin/test/conftest.py` so that it can be used from any test script.  Something like (untested):

```python
@pytest.fixture
def appconfig():
  appconfig = AppConfig()
  with appconfig._as_current():
    yield appconfig
```

That can then be used in a test like this:
```python
def test_something(appconfig):
  appconfig.check_path = '/foo/bar'
  some_function_that_expects_current_appconfig()
```

This is a bit of a challenging puzzle, but hopefully that helps point you in a fruitful direction.

**Comment by vishakhanihore** [comment]
> pytest fixture

Got your point, will make changes by today 👍

**Comment by djmitche** [comment]
@vishakhanihore any chance you want to finish this up?

**Pull request closed without merging**
